[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[project]
name = "al-otto"
dynamic = ["version"]
description = "The ottomatic video engine"
authors = [
    {name = "Quaternion Media", email = "qm@quaternion.media"}
]
dependencies = ["fastapi<1.0.0,>=0.94.0", "moviepy<2.0.0,>=1.0.3", "pydantic<2.0.0,>=1.10.5"]
requires-python = ">=3.8.1,<4.0"
readme = "README.md"
license = {text = "MIT"}

[project.urls]
homepage = "https://github.com/quaternionmedia/otto"
documentation = "https://quaternionmedia.github.io/otto/"
repository = "https://github.com/quaternionmedia/otto"

[project.optional-dependencies]
render = [
    "gizeh >= 0.1.11",
    "bezier >= 2021.2.12",
    "tqdm >= 4.64.1"
]
test = [
    "pytest >= 7.2.1",
    "httpx >= 0.23.3",
    "pytest-cov >= 4.0.0",
    "pytest-xdist>=3.2.1",
]
docs = [
    "mkdocs >= 1.4.2",
    "mkdocs-material >= 9.1.2",
    "mkdocs-git-revision-date-localized-plugin >= 1.2.0",
    "mike @ git+https://github.com/jimporter/mike.git@063c93e9cce7c82939c7d47e6d33f99b24bba372",
    "mkdocstrings[python] >= 0.20.0",
]

[tool.pdm.dev-dependencies]
dev = [
    "uvicorn >= 0.21.1",
    "black >= 23.1.0",
    "flake8 >= 6.0.0"
]
nox = ["nox >= 2022.11.21"]


[tool.pdm]
version = { source = "file", path = "otto/_version.py" }

[tool.pytest.ini_options]
testpaths = ["tests"]
